[package]
name = "parser"
version = "0.1.0"
authors = ["Josh Karns <jkarns275@gmail.com>"]

[dependencies]
pest = { git = "https://github.com/jkarns275/pest", branch = "master", version = "2.0.2"}
libhcc = { path = "libhcc/" }
argparse = "0.2.2"

[[bin]]
name="hcc"
path="src/cli.rs"